### ISSUE TITLE
usage?

### ISSUE THREAD

**Issue by bcherny** [anilanar/tentacle.js#1]
this looks pretty cool, is it usable?

**Comment by anilanar** [comment]
I will do some major refactoring to get rid of objects defined on window object or will make it optional. This would be ready to use till this weekend.

**Comment by anilanar** [comment]
@bcherny 
Sorry for the long wait, I actually took my time on this.
If you are still interested, you can try out [tentacle-v0.1](https://github.com/anilanar/tentacle.js/tree/tentacle-v0.1) branch. I will integrate TravisCI and add some other gulp tasks before merging it to master.
